### ISSUE TITLE
Extend query and tests request with a settings field

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumukit#57]
Runners should accept a `settings` field in both `query` and `test` requests, which contains an arbitrary runner-dependent dictionary of settings. For example, a JavaScript runner may support the following:

```json
{
   "content": "....",
   "test": "....", 
   "settings": {  "strict": true }   
} 
```

while a Haskell runner might support the following: 
 

```json
{
   "content": "....",
   "test": "....", 
   "settings": {  "allowed_ghc_extensions": ["QuasiQuotes", "GenericDeriving" ] }   
} 
```

**Comment by flbulgarelli** [comment]
We should also extend mumukit so that runners can declare they supports this feature.

**Comment by julian-berbel** [comment]
> We should also extend mumukit so that runners can declare they supports this feature.

We don't really need to do anything to have them support it. We're sending settings as part of the request's body, so it'll be automatically available for runners as `req[:settings]` (I just checked this just in case).

Were you thinking of something else @flbulgarelli ?

**Comment by flbulgarelli** [comment]
Does metadata expose this suport?

**Comment by julian-berbel** [comment]
You mean in metadata_hook? Nope. Since it's not something related to the runner itself, should it?

Also, would this be a descriptive field, or would it be an expression of will?

If it's the latter, shouldn't we just add it to the language's settings in domain, like we did with feedback, multifile, etc.?

Also, you're on holidays! answer this on monday!
